### ISSUE TITLE
Unknown authentication strategy "oidc"

### ISSUE THREAD

**Issue by hampsterx** [rdegges/okta-express-blog#1]
tried updating deps to

```
"@okta/oidc-middleware": "^0.1.3",
    "@okta/okta-sdk-nodejs": "^1.2.0",
```

Tried this suggestion.

https://github.com/okta/okta-oidc-js/issues/68

However it still fails with:

```
url: 'https://devolitemp.okta.com/oauth2/default/oauth2/default/.well-known/openid-configuration',
statusCode: 404,
statusMessage: 'Not Found',
```
Same situation is noted here:

https://developer.okta.com/blog/2018/06/28/tutorial-build-a-basic-crud-app-with-node

Following this guide is the same:

https://developer.okta.com/quickstart/#/okta-sign-in-page/nodejs/express

So basically not a good start. now reviewing other hosted auth solutions :(

**Comment by rdegges** [comment]
It looks like the URL you're using is invalid. You copy+pasted it incorrectly. EG: your URL shows `/oauth2/default/oauth2/default` (you have it repeated twice) =)
